"""バッチ2（第67〜80号議案）の主張台帳の仕様。形式は spec_b1.py と同じ。"""
from spec_b1 import SESSION, SUBMIT, pending

JOREI_SUBMIT = lambda p: (p, "議案本文 提出日・提出者", "令和８年９月１６日 … 新宿区長 … 吉住 … 健一")

BILLS = []


def std(slug_n, prefix, main, F, easy, normal, hard):
    BILLS.append(dict(slug=f"shinjuku-2026-r3-gian-{slug_n}", prefix=prefix, facts=F, claims=easy + normal + hard, main=main))


# ---------------------------------------------------------------------------
# 第67号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P67"),
    "base": ("P67", "議案本文", "新宿区公益保護のための通報に関する条例（平成18年新宿区条例第39号）の一部を次のように改正する"),
    "kaime": ("P67", "改め文", "第3条第1項中「第3条第1号」を「第3条第1項第1号」に改める"),
    "shiko": ("P67", "附則", "この条例は、令和8年12月1日から施行する"),
    "reason": ("P67", "提案理由", "公益通報者保護法の一部を改正する法律（令和7年法律第62号）の施行に伴い、規定を整備する必要があるため"),
    "ov": ("OJ", "条例関係 第67号議案", "公益通報者保護法の改正に伴い、引用条項を改める。 … 令和 8 年 12 月 1 日"),
}
std(67, "R67", "P67", F, [
    ("easy", "title", "見出し: 公益通報の条例で引用する法律の条項を直す", "ov"),
    ("easy", "summary", "要約: 公益通報者保護法の改正に伴い引用条項を改める", "ov"),
    ("easy", "summary", "要約: 施行は2026年12月1日", "shiko"),
    ("easy", "content", "対象は新宿区公益保護のための通報に関する条例", "base"),
    ("easy", "content", "公益通報者保護法の改正に伴い規定を整備する", "reason"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "第3条第1項の「第3条第1号」を「第3条第1項第1号」にする", "kaime"),
    ("easy", "content", "施行は2026年（令和8年）12月1日（火）", "shiko"),
    *pending("easy"),
    ("easy", "content", "法律の改正内容、区の通報制度への影響は書かれていない", None),
], [
    ("normal", "title", "見出し: 公益通報者保護法の改正に合わせた引用条項の整理", "ov"),
    ("normal", "summary", "要約: 引用する条項の表記を改める", "kaime"),
    ("normal", "summary", "要約: 施行は令和8年12月1日", "shiko"),
    ("normal", "content", "令和8年9月16日に区長が提出、平成18年新宿区条例第39号の一部改正", "base"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "概要資料の説明", "ov"),
    ("normal", "content", "改め文は1か所", "kaime"),
    ("normal", "content", "提案理由", "reason"),
    ("normal", "content", "施行日", "shiko"),
    *pending("normal"),
    ("normal", "content", "法改正の内容、運用の変化は書かれていない", None),
], [
    ("hard", "title", "見出し: 議案名", "base"),
    ("hard", "summary", "要約: 改め文の内容", "kaime"),
    ("hard", "summary", "要約: 提案理由", "reason"),
    ("hard", "summary", "要約: 施行日", "shiko"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "対象条例", "base"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "改め文", "kaime"),
    ("hard", "content", "概要資料の説明と施行日", "ov"),
    ("hard", "content", "附則", "shiko"),
    *pending("hard"),
    ("hard", "content", "確定条文、法改正の内容・施行日、運用への影響は資料にない", None),
])

# ---------------------------------------------------------------------------
# 第68号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P68"),
    "base": ("P68", "議案本文", "新宿区立しんじゅく多文化共生プラザ条例（平成17年新宿区条例第37号）の一部を次のように改正する"),
    "ichi": ("P68", "改め文 第2条", "第2条中「東京都新宿区歌舞伎町二丁目44番1号」を「東京都新宿区四谷三栄町10番16号」に改める"),
    "jikan": ("P68", "改め文 第5条", "第5条中「午後9時」を「午後5時」に改める"),
    "kyukan": ("P68", "改め文 第6条", "第6条第1号を次のように改める。 … 日曜日及び土曜日 … 第6条第2号中「の日」の次に「（前号に掲げる日を除く。）」を加え、同号を同条第3号とし、同条第1号の次に次の1号を加える。 … 国民の祝日に関する法律（昭和23年法律第178号）に規定する休日"),
    "shiko": ("P68", "附則", "この条例は、令和9年4月5日から施行する"),
    "reason": ("P68", "提案理由", "新宿区立しんじゅく多文化共生プラザの移転に伴い、その位置、利用時間及び休館日を変更する必要があるため"),
    "ov": ("OJ", "条例関係 第68号議案", "新宿区立しんじゅく多文化共生プラザの移転に伴い、所要の … 改正を行う。"),
    "ov_table": ("OJ", "条例関係 第68号議案 現行・移転後", "位置 東京都新宿区歌舞伎町二 東京都新宿区四谷三栄町 … 丁目 44 番 1 号 10 番 16 号 … 利用時間 午前9時から午後9時まで 午前9時から午後5時まで … 休館日 ⑴ 毎月の第 2 水曜日及 ⑴ 日曜日及び土曜日 … ⑵ 国民の祝日に関する … 12月29日から翌年の … 令 和 9 年 4 月 5 日"),
}
std(68, "R68", "P68", F, [
    ("easy", "title", "見出し: 多文化共生プラザが四谷三栄町に移る", "ichi"),
    ("easy", "summary", "要約: 四谷三栄町に移る", "ichi"),
    ("easy", "summary", "要約: 利用時間は午後5時まで", "jikan"),
    ("easy", "summary", "要約: 土日と休日が休館日になる", "kyukan"),
    ("easy", "summary", "要約: 施行は2027年4月5日", "shiko"),
    ("easy", "content", "プラザの移転に伴い、位置・利用時間・休館日を変える", "reason"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "場所: 歌舞伎町二丁目44番1号 → 四谷三栄町10番16号", "ichi"),
    ("easy", "content", "時間: 午前9時〜午後9時 → 午前9時〜午後5時", "ov_table"),
    ("easy", "content", "休館日: 第2・第4水曜日と年末年始 → 日曜日・土曜日、休日、年末年始", "ov_table"),
    ("easy", "content", "休館日の改め文", "kyukan"),
    ("easy", "content", "施行は2027年（令和9年）4月5日（月）", "shiko"),
    *pending("easy"),
    ("easy", "content", "移転の理由、新しい建物、事業の変化、現在地の利用期限は書かれていない", None),
], [
    ("normal", "title", "見出し: 移転で場所・利用時間・休館日を変更", "reason"),
    ("normal", "summary", "要約: 位置の変更", "ichi"),
    ("normal", "summary", "要約: 利用時間の短縮", "jikan"),
    ("normal", "summary", "要約: 休館日の変更", "kyukan"),
    ("normal", "summary", "要約: 施行日", "shiko"),
    ("normal", "content", "令和8年9月16日に区長が提出、平成17年新宿区条例第37号", "base"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "提案理由", "reason"),
    ("normal", "content", "概要資料の現行・移転後の対比表", "ov_table"),
    ("normal", "content", "利用時間12時間→8時間（午前9時〜午後9時／午後5時からの計算）、休館日の変化", "ov_table"),
    ("normal", "content", "施行日", "shiko"),
    *pending("normal"),
    ("normal", "content", "移転の理由等は書かれていない", None),
], [
    ("hard", "title", "見出し: 議案名", "base"),
    ("hard", "summary", "要約: 第2条・第5条・第6条の改正", "ichi"),
    ("hard", "summary", "要約: 利用時間の終期", "jikan"),
    ("hard", "summary", "要約: 休館日", "kyukan"),
    ("hard", "summary", "要約: 施行日", "shiko"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "対象条例", "base"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "改め文 第2条", "ichi"),
    ("hard", "content", "改め文 第5条", "jikan"),
    ("hard", "content", "改め文 第6条", "kyukan"),
    ("hard", "content", "概要資料の現行・移転後", "ov_table"),
    ("hard", "content", "概要資料の説明", "ov"),
    ("hard", "content", "附則", "shiko"),
    *pending("hard"),
    ("hard", "content", "移転の理由、施設概要、事業の変化、現在地の終了日、全文は資料にない", None),
])

# ---------------------------------------------------------------------------
# 第69号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P69"),
    "base": ("P69", "議案本文", "新宿区乳児等通園支援事業の実施に関する条例（令和8年新宿区条例第1号）の一部を次のように改正する"),
    "kaime": ("P69", "改め文 第7条第3項", "第7条第3項中「乳児等通園支援事業を利用した日において保護者が生活保護法（昭和25年法律第144号）第6条第1項に規定する被保護者である」を「次に掲げる」に、「無料とする」を「区長が別に定めるところによるものとする」に改め、同項に次の各号を加える"),
    "go1": ("P69", "改め文 第7条第3項第1号", "乳児等通園支援事業を利用した日において保護者が生活保護法（昭和25年法律第144号）第6条第1項に規定する被保護者である場合"),
    "go2": ("P69", "改め文 第7条第3項第2号", "保護者及び保護者と同一の世帯に属する者が地方税法（昭和25年法律第226号）の規定による区市町村民税を課されない者である場合（前号に掲げる場合を除く。）"),
    "go3": ("P69", "改め文 第7条第3項第3号", "保護者及び保護者と同一の世帯に属する者について地方税法の規定による区市町村民税の同法第292条第1項第2号に規定する所得割の額を合算した額が … 7万 … 7,101円未満である場合 … （前2号に掲げる場合を除く。）"),
    "go4": ("P69", "改め文 第7条第3項第4号", "区長が対象乳幼児及び保護者の心身の状況及び養育環境等を踏まえ、第1項の規定により納付する利用料を軽減することが適当であると認める場合（前3号に掲げる場合を除く。）"),
    "sakujo": ("P69", "改め文", "第7条第4項から第6項までを削る"),
    "shiko": ("P69", "附則", "この条例は、公布の日から施行する"),
    "keika": ("P69", "附則 経過措置", "この条例による改正後の第7条第3項の規定は、この条例の施行の日以後の利用に係る利用料について適用し、同日前の利用に係る利用料については、なお従前の例による"),
    "reason": ("P69", "提案理由", "特定乳児等通園支援に要する費用の額の算定に関する基準（令和8年こども家庭庁告示第8号）の適用等を踏まえ、新宿区が実施する乳児等通園支援事業の利用料を改める必要があるため"),
    "ov": ("OJ", "条例関係 第69号議案", "特定乳児等通園支援に要する費用の額の算定に関する基準 … （国告示）の適用等を踏まえ、区が実施する乳児等通園支援事 … 業の利用者の属する世帯が生活困窮家庭等である場合の利用 … 料は、区長が別に定めることとする。 … 公布の日"),
}
std(69, "R69", "P69", F, [
    ("easy", "title", "見出し: 乳児等通園支援事業の利用料の決まりを変える", "kaime"),
    ("easy", "summary", "要約: 利用料の決まりを変える", "kaime"),
    ("easy", "summary", "要約: 生活困窮家庭等の利用料は区長が別に定める", "ov"),
    ("easy", "summary", "要約: 対象は4つの場合", "go4"),
    ("easy", "summary", "要約: 公布の日から施行", "shiko"),
    ("easy", "content", "区が実施する乳児等通園支援事業の利用料を改める", "reason"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "国の告示の適用等を踏まえ、生活困窮家庭等の利用料は区長が別に定める", "ov"),
    ("easy", "content", "「無料とする」を「区長が別に定める」に改める（改め文から、被保護者の場合の規定と読み取れる範囲）", "kaime"),
    ("easy", "content", "1: 生活保護の被保護者", "go1"),
    ("easy", "content", "2: 世帯全員が住民税非課税", "go2"),
    ("easy", "content", "3: 所得割の合算額が7万7,101円未満", "go3"),
    ("easy", "content", "4: 区長が軽減を適当と認める場合", "go4"),
    ("easy", "content", "第4項から第6項を削る", "sakujo"),
    ("easy", "content", "公布の日から施行", "shiko"),
    ("easy", "content", "施行日以後の利用に適用、前の利用は従前の例", "keika"),
    *pending("easy"),
    ("easy", "content", "区長が定める額、生活保護世帯が引き続き無料か、削る項の内容は書かれていない", None),
], [
    ("normal", "title", "見出し: 生活困窮家庭等の利用料を区長が別に定める形に", "ov"),
    ("normal", "summary", "要約: 「無料とする」を改める", "kaime"),
    ("normal", "summary", "要約: 対象の4つの場合", "go3"),
    ("normal", "summary", "要約: 公布の日から施行", "shiko"),
    ("normal", "content", "令和8年9月16日に区長が提出、令和8年新宿区条例第1号", "base"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "概要資料の説明", "ov"),
    ("normal", "content", "第7条第3項の改め文", "kaime"),
    ("normal", "content", "第1号", "go1"),
    ("normal", "content", "第2号", "go2"),
    ("normal", "content", "第3号", "go3"),
    ("normal", "content", "第4号", "go4"),
    ("normal", "content", "第4項から第6項を削る", "sakujo"),
    ("normal", "content", "施行日", "shiko"),
    ("normal", "content", "経過措置", "keika"),
    *pending("normal"),
    ("normal", "content", "区長が定める額、生活保護世帯が無料のままか、削る項の内容は確認できない", None),
], [
    ("hard", "title", "見出し: 議案名", "base"),
    ("hard", "summary", "要約: 第7条第3項の改正", "kaime"),
    ("hard", "summary", "要約: 第4〜6項の削除", "sakujo"),
    ("hard", "summary", "要約: 施行と適用", "keika"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "対象条例", "base"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "第7条第3項の改め文", "kaime"),
    ("hard", "content", "第1号", "go1"),
    ("hard", "content", "第2号", "go2"),
    ("hard", "content", "第3号", "go3"),
    ("hard", "content", "第4号", "go4"),
    ("hard", "content", "第4〜6項の削除", "sakujo"),
    ("hard", "content", "概要資料の説明", "ov"),
    ("hard", "content", "附則 施行期日", "shiko"),
    ("hard", "content", "附則 経過措置", "keika"),
    ("hard", "content", "改正前の規定は被保護者の場合に無料とする旨（改め文から読み取れる範囲）", "kaime"),
    *pending("hard"),
    ("hard", "content", "区長が定める額、削る項の内容、全文、告示の内容、対象世帯数は資料にない", None),
])

# ---------------------------------------------------------------------------
# 第70号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P70"),
    "base1": ("P70", "第1条", "新宿区家庭的保育事業等の設備及び運営に関する基準を定める条例（平成26年新宿区条例第28号）の一部を次のように改正する。 … 第14条を次のように改める"),
    "base2": ("P70", "第2条", "新宿区乳児等通園支援事業の設備及び運営に関する基準を定める条例（令和7年新宿区条例第45号）の一部を次のように改正する"),
    "art14": ("P70", "第1条による第14条", "家庭的保育事業者等は、法第34条の16第4項において準用する法第21条の5の18第4項の規定に基づき、児童対象性暴力等（学校設置者等及び民間教育保育等事業者による児童対象性暴力等の防止等のための措置に関する法律（令和6年法律第69号）第2条第2項に規定する児童対象性暴力等をいう。以下この条において同じ。）を防止し、及び児童対象性暴力等が行われた場合に利用乳幼児を適切に保護するため、児童等対象業務従事者（利用乳幼児と接する業務に従事する者のうち、支配性、継続性及び閉鎖性のある環境の下で当該利用乳幼児に接する者をいう。）に係る犯罪事実確認（同法第4条第1項に規定する犯罪事実確認をいう。）その他の必要な措置を講じなければならない"),
    "art14_2": ("P70", "第2条による第14条の2", "第14条の2 … 乳児等通園支援事業者は、法第34条の16第4項において準用する法第21条の5の18第4項の規定に基づき"),
    "seibi": ("P70", "第2条 規定整備", "第10条の見出しを「（乳児等通園支援事業所の職員の一般的要件）」に改め、同条中「乳児等通園支援事業者」を「乳児等通園支援事業所」に改める。 … 第11条の見出し及び同条第1項中「乳児等通園支援事業者」を … 第14条の見出し中「防止」を「禁止」に改め"),
    "seibi2": ("P70", "第2条 規定整備", "第17条第7号中「並びに」を「その他の」に改める。 … 第19条第1項中「乳児等通園支援事業者」を「乳児等通園支援事業所」に改める。 … 第21条第3項中「係る利用定員」の次に「（子ども・子育て支援法（平成24年法律第65号）第27条第1項又は第29条第1項の確認において定める利用定員をいう。）」を加える。 … 第27条後段を削る。 … 第28条中「及びその」の次に「乳児等通園支援事業所の」を加える"),
    "shiko": ("P70", "附則", "この条例は、令和8年12月25日から施行する"),
    "reason": ("P70", "提案理由", "学校設置者等及び民間教育保育等事業者による児童対象性暴力等の防止等のための措置に関する法律施行規則（令和7年内閣府令第104号）の施行による家庭的保育事業等の設備及び運営に関する基準（平成26年厚生労働省令第61号）の改正等に伴い、児童対象性暴力等の防止等に係る措置を新たに定めるほか、規定を整備する必要があるため"),
    "ov": ("OJ", "条例関係 第70号議案", "家庭的保育事業等の設備及び運営に関する基準を定めてい … る内閣府令の改正等に伴い、児童対象性暴力等の防止等に係る … 措置を新たに定める。 … 令和 8 年 12 月 25 日"),
}
std(70, "R70", "P70", F, [
    ("easy", "title", "見出し: 保育の事業で子どもへの性暴力を防ぐ決まりを作る", "art14"),
    ("easy", "summary", "要約: 2つの基準条例を変える", "base2"),
    ("easy", "summary", "要約: 事業者は防止の措置をしなければならない", "art14"),
    ("easy", "summary", "要約: 施行は2026年12月25日", "shiko"),
    ("easy", "content", "家庭的保育事業等の基準条例を変える", "base1"),
    ("easy", "content", "乳児等通園支援事業の基準条例を変える", "base2"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "内閣府令の改正等に伴い、児童対象性暴力等の防止等の措置を定める", "ov"),
    ("easy", "content", "防止・保護のため、犯罪事実確認その他の必要な措置を講じなければならない（対象は支配性・継続性・閉鎖性のある環境で接する者）", "art14"),
    ("easy", "content", "第14条を改め、第14条の2を加える", "art14_2"),
    ("easy", "content", "「乳児等通園支援事業者」を「乳児等通園支援事業所」に直す箇所がある", "seibi"),
    ("easy", "content", "施行は2026年（令和8年）12月25日（金）", "shiko"),
    *pending("easy"),
    ("easy", "content", "確認の方法、対象事業所数、現行第14条の内容は書かれていない", None),
], [
    ("normal", "title", "見出し: 事業者に児童対象性暴力等の防止措置を義務付け", "art14"),
    ("normal", "summary", "要約: 2つの基準条例を改める", "base1"),
    ("normal", "summary", "要約: 犯罪事実確認その他の必要な措置を義務付け", "art14"),
    ("normal", "summary", "要約: 規定の整備", "seibi2"),
    ("normal", "summary", "要約: 施行日", "shiko"),
    ("normal", "content", "令和8年9月16日に区長が提出、対象の2条例", "base2"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "家庭的保育の条例（平成26年新宿区条例第28号）", "base1"),
    ("normal", "content", "概要資料の説明", "ov"),
    ("normal", "content", "提案理由", "reason"),
    ("normal", "content", "第14条（家庭的保育）の内容", "art14"),
    ("normal", "content", "第14条の2（乳児等通園支援）", "art14_2"),
    ("normal", "content", "規定整備（第10条・第11条・第14条見出し）", "seibi"),
    ("normal", "content", "規定整備（第17条・第19条・第21条・第27条・第28条）", "seibi2"),
    ("normal", "content", "施行日", "shiko"),
    *pending("normal"),
    ("normal", "content", "手続、対象数、現行第14条、第27条後段の内容、内閣府令と厚生労働省令の関係は書かれていない", None),
], [
    ("hard", "title", "見出し: 議案名", "base2"),
    ("hard", "summary", "要約: 第1条で第14条を全部改める", "base1"),
    ("hard", "summary", "要約: 第2条で第14条の2を加える", "art14_2"),
    ("hard", "summary", "要約: 第2条の規定整備", "seibi2"),
    ("hard", "summary", "要約: 施行日", "shiko"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "対象条例（家庭的保育）", "base1"),
    ("hard", "content", "対象条例（乳児等通園支援）", "base2"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "第14条の条文", "art14"),
    ("hard", "content", "第2条の改正表（第10条・第11条・第14条）", "seibi"),
    ("hard", "content", "第2条の改正表（第14条の2）", "art14_2"),
    ("hard", "content", "第2条の改正表（第17条〜第28条）", "seibi2"),
    ("hard", "content", "概要資料の説明", "ov"),
    ("hard", "content", "附則", "shiko"),
    *pending("hard"),
    ("hard", "content", "現行第14条、第27条後段、「法」の題名、手続・対象数、府令と省令の関係は資料にない", None),
])

# ---------------------------------------------------------------------------
# 第71号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P71"),
    "base": ("P71", "議案本文", "新宿区景観まちづくり条例（平成20年新宿区条例第67号）の一部を次のように改正する"),
    "kaime": ("P71", "改め文", "第12条第2項中「同条第7項各号」を「同条第8項各号」に改め、同条第3項中「第16条第7項第11号」を「第16条第8項第12号」に改める。 … 第17条中「第16条第7項各号」を「第16条第8項各号」に改める"),
    "shiko": ("P71", "附則", "この条例は、都市再生特別措置法等の一部を改正する法律（令和8年法律第23号）の施行の日又はこの条例の公布の日のいずれか遅い日から施行する"),
    "reason": ("P71", "提案理由", "都市再生特別措置法等の一部を改正する法律（令和8年法律第23号）の施行による景観法（平成16年法律第110号）の改正に伴い、規定を整備する必要があるため"),
    "ov": ("OJ", "条例関係 第71号議案", "景観法の改正により、都市再生特別措置法に基づく特定固有 … 魅力形成建築物の増築等の届出がされたときは、併せて景観法 … に基づく増築等の届出がされたものとみなす規定が追加され … たこと等に伴い、引用条項を改める。"),
}
std(71, "R71", "P71", F, [
    ("easy", "title", "見出し: 景観の条例で引用する法律の条項を直す", "ov"),
    ("easy", "summary", "要約: 景観法の改正に伴い番号を直す", "reason"),
    ("easy", "summary", "要約: 施行日の定め", "shiko"),
    ("easy", "content", "新宿区景観まちづくり条例が対象", "base"),
    ("easy", "content", "景観法の改正に伴い規定を整備する", "reason"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "都市再生特別措置法の届出で景観法の届出とみなす規定が追加された", "ov"),
    ("easy", "content", "3か所の番号の変更", "kaime"),
    ("easy", "content", "改正法の施行日と公布日のいずれか遅い日から", "shiko"),
    *pending("easy"),
    ("easy", "content", "改正法の施行日、手続の変化は書かれていない", None),
], [
    ("normal", "title", "見出し: 景観法の改正に合わせた引用条項の整理", "ov"),
    ("normal", "summary", "要約: 引用条項の番号を改める", "kaime"),
    ("normal", "summary", "要約: 施行日", "shiko"),
    ("normal", "content", "令和8年9月16日に区長が提出、平成20年新宿区条例第67号", "base"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "概要資料の説明", "ov"),
    ("normal", "content", "提案理由", "reason"),
    ("normal", "content", "改正箇所の表", "kaime"),
    ("normal", "content", "施行日", "shiko"),
    *pending("normal"),
    ("normal", "content", "施行日、届出手続の変化、対象建築物は書かれていない", None),
], [
    ("hard", "title", "見出し: 議案名", "base"),
    ("hard", "summary", "要約: 改め文", "kaime"),
    ("hard", "summary", "要約: 提案理由", "reason"),
    ("hard", "summary", "要約: 施行日", "shiko"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "対象条例", "base"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "改め文", "kaime"),
    ("hard", "content", "概要資料の説明", "ov"),
    ("hard", "content", "項・号が1つずつ追加されたことと整合（改め文の番号変更からの読み取り）", "kaime"),
    ("hard", "content", "附則", "shiko"),
    *pending("hard"),
    ("hard", "content", "改正法の施行日、引用先の特定、対象建築物、運用への影響は資料にない", None),
])

# ---------------------------------------------------------------------------
# 第72号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P72"),
    "base": ("P72", "議案本文", "新宿区立の小学校、中学校及び特別支援学校の非常勤の学校医、学校歯科医及び学校薬剤師の公務災害補償に関する条例（平成 … 14年 … 新宿区条例第24号）の一部を次のように改正する"),
    "kaime": ("P72", "改め文", "第13条第2項第2号中「8万5,490円」を「9万790円」に改め、同項第4号中「4万2,700円」を「4万5,400円」に改める。 … 第27条中「31万5,000円」を「33万円」に改める"),
    "shiko": ("P72", "附則 第1項", "この条例は、令和8年11月1日から施行する"),
    "keika": ("P72", "附則 第2項", "第13条第2項及び第27条の規定は、令和8年9月1日（以下「適用日」という。）以後に支給すべき事由が生じた介護補償及び葬祭補償について適用し、適用日前に支給すべき事由が生じた介護補償及び葬祭補償については、なお従前の例による"),
    "uchibarai": ("P72", "附則 第3項", "として支払われた金額は、これらに相当する改正後の条例の規定に基づく補償の内払とみなす"),
    "reason": ("P72", "提案理由", "公立学校の学校医、学校歯科医及び学校薬剤師の公務災害補償の基準を定める政令の一部を改正する政令（令和8年政令第165号）の施行等に伴い、介護補償の額及び葬祭補償の額を改定する必要があるため"),
    "ov": ("OJ", "条例関係 第72号議案", "区立学校医等の公務災害補償額の算定基礎としている都立 … 学校の学校医、学校歯科医及び学校薬剤師の公務災害補償に関 … する条例の改正に合わせ、次のとおり介護補償の額及び葬祭補 … 償の額を改定する。"),
    "ov_table": ("OJ", "条例関係 第72号議案 介護補償・葬祭補償", "常時介護を要 最高限度額 186,050 円 改定なし … 最低保障額 85,490 円 90,790 円 … 随時介護を要 最高限度額 92,980 円 改定なし … 最低保障額 42,700 円 45,400 円 … 31 万 5,000 円 ＋ 補償基礎額×30 … 33 万円 ＋ 補償基礎額×30 … 令 和 8 年 11 月 1 日"),
}
std(72, "R72", "P72", F, [
    ("easy", "title", "見出し: 介護補償と葬祭補償の額を上げる", "kaime"),
    ("easy", "summary", "要約: 区立学校の学校医・学校歯科医・学校薬剤師", "base"),
    ("easy", "summary", "要約: 介護補償の最低保障額と葬祭補償を上げる", "ov_table"),
    ("easy", "summary", "要約: 施行2026年11月1日、適用2026年9月1日", "keika"),
    ("easy", "content", "区立の小中・特別支援学校の非常勤の学校医等の公務災害補償", "base"),
    ("easy", "content", "介護補償と葬祭補償の額を改定", "reason"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "都立学校の条例の改正に合わせる（概要資料）", "ov"),
    ("easy", "content", "議案には国の政令の改正も理由として書かれている", "reason"),
    ("easy", "content", "介護補償の表（最高限度額は改定なし、最低保障額を引き上げ）", "ov_table"),
    ("easy", "content", "葬祭補償 31万5,000円→33万円（＋補償基礎額×30）", "kaime"),
    ("easy", "content", "施行2026年（令和8年）11月1日（日）", "shiko"),
    ("easy", "content", "適用2026年9月1日（火）以後の事由", "keika"),
    ("easy", "content", "旧額の支払いは内払いとみなす", "uchibarai"),
    *pending("easy"),
    ("easy", "content", "受給者数、支出増は書かれていない", None),
], [
    ("normal", "title", "見出し: 介護補償・葬祭補償の額を引き上げ", "kaime"),
    ("normal", "summary", "要約: 最低保障額と葬祭補償の引き上げ額", "ov_table"),
    ("normal", "summary", "要約: 施行日・適用日", "keika"),
    ("normal", "content", "令和8年9月16日に区長が提出、平成14年新宿区条例第24号", "base"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "概要資料の説明", "ov"),
    ("normal", "content", "提案理由", "reason"),
    ("normal", "content", "介護補償の額の表", "ov_table"),
    ("normal", "content", "葬祭補償の額", "kaime"),
    ("normal", "content", "施行日", "shiko"),
    ("normal", "content", "適用日と適用範囲", "keika"),
    ("normal", "content", "内払い", "uchibarai"),
    *pending("normal"),
    ("normal", "content", "受給者数、支出増、都条例の改正内容は書かれていない", None),
], [
    ("hard", "title", "見出し: 議案名", "base"),
    ("hard", "summary", "要約: 改め文の3か所", "kaime"),
    ("hard", "summary", "要約: 施行日・適用日・内払", "keika"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "対象条例", "base"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "改め文の表", "kaime"),
    ("hard", "content", "概要資料の趣旨", "ov"),
    ("hard", "content", "概要資料の表", "ov_table"),
    ("hard", "content", "根拠について概要資料は都条例、議案本文は政令を挙げる", "reason"),
    ("hard", "content", "附則 第1項", "shiko"),
    ("hard", "content", "附則 第2項", "keika"),
    ("hard", "content", "附則 第3項", "uchibarai"),
    *pending("hard"),
    ("hard", "content", "全文、政令・都条例の改正内容と関係、受給者数・支出増は資料にない", None),
])

# ---------------------------------------------------------------------------
# 第73〜75号議案（ESCO）
# ---------------------------------------------------------------------------
import importlib.util, sys
spec = importlib.util.spec_from_file_location("esco", "esco.py")
_src = open("esco.py").read().split("open(\"chunk-73-75.ts\"")[0]
_ns = {}
exec(_src, _ns)
ESCO = _ns["BILLS"]
PDFKEY = {73: "P73", 74: "P74", 75: "P75"}
OV_LINES = {
    73: ("東京都新宿区市谷仲之町 2 番 42 号 外 5 か所", "2 億 2,990 万円", "東京都品川区二葉二丁目 9 番 15 号 … 東京ガスリノベーション株式会社 … 代表取締役 高橋 稔 … 資本金 1 億円"),
    74: ("東京都新宿区内藤町 87 番地 外 2 か所", "2 億 5,702 万 6,000 円", "東京都新宿区新宿六丁目 7 番 6 号 … 東邦電気工事株式会社 … 代表取締役社長 豊岡 良至 … 資本金 4,000 万円"),
    75: ("東京都新宿区大久保二丁目 12 番 7 号 外 5 か所", "2 億 7,610 万円", "東京都新宿区百人町二丁目 24 番 10 号 … 日東電工株式会社 … 代表取締役 本間 正明 … 資本金 2,000 万円"),
}
for b in ESCO:
    n = b["n"]; p = PDFKEY[n]
    place, amount, party = OV_LINES[n]
    F = {
        "session": SESSION,
        "submit": JOREI_SUBMIT(p),
        "mokuteki": (p, "議案本文 前文・1 契約の目的", f"ＥＳＣＯ事業による{b['facility']}照明ＬＥＤ … 化工事等施行のため、下記のとおり工事等委託契約を締結する" if n != 75 else "ＥＳＣＯ事業による新宿区大久保特別出張所外 … 10施設照明ＬＥ … Ｄ化工事等施行のため、下記のとおり工事等委託契約を締結する"),
        "houhou": (p, "議案本文 2 契約の方法", "制限付一般競争入札による契約"),
        "kingaku": (p, "議案本文 3 契約金額", b["amount"]),
        "aite": (p, "議案本文 4 契約の相手方", f"{b['address']} … {b['company']}"),
        "shishutsu": (p, "議案本文 5 支出科目等", "令和9年度 … 債務負担行為 … 令和10年度 … 債務負担行為 … 令和11年度 … 令和12年度 … 令和13年度 … 令和14年度 … 債務負担行為"),
        "reason": (p, "提案理由", "化工事等を施行する必要があるため" if n != 75 else "Ｄ化工事等を施行する必要があるため"),
        "gaiyo": ("OJ", f"議決案件関係 第{n}号議案 1 工事概要", "省エネルギーに関する包括的なサービス（調査、設計、施工、その後の省エネル … ギー効果の検証や助言、効果保証等）を提供するＥＳＣＯ事業により"),
        "basho": ("OJ", f"議決案件関係 第{n}号議案 2 工事場所", place),
        "tsukihi": ("OJ", f"議決案件関係 第{n}号議案 3 契約月日", "仮契約 令和 8 年 7 月 31 日（金） … 本契約 議決日の翌日"),
        "kikan": ("OJ", f"議決案件関係 第{n}号議案 4 契約期間", "本契約締結日の翌日から令和 15 年 2 月 28 日まで"),
        "ov_aite": ("OJ", f"議決案件関係 第{n}号議案 6・7", f"{amount} … {party}"),
        "hokano": ("OJ", "議決案件関係 第73〜75号議案", "ＥＳＣＯ事業による新宿区立防災センター外 11 施設照明ＬＥＤ化工事等委託契約 … ＥＳＣＯ事業による新宿区四谷特別出張所外 6 施設照明ＬＥＤ化工事等委託契約 … ＥＳＣＯ事業による新宿区大久保特別出張所外 10 施設照明ＬＥＤ化工事等委託契約"),
    }
    C = [
        ("easy", "title", f"見出し: {b['short']}の照明をLED化する契約（「外{ {73: 11, 74: 6, 75: 10}[n] }施設」を本体と合わせた施設数で表記）", "mokuteki"),
        ("easy", "summary", "要約: 照明をLED化する", "mokuteki"),
        ("easy", "summary", "要約: ESCO事業の契約", "gaiyo"),
        ("easy", "summary", f"要約: 金額{b['amount']}、相手{b['company']}", "aite"),
        ("easy", "summary", "要約: 契約は2033年2月28日まで", "kikan"),
        ("easy", "content", "ESCO事業により照明をLED化する工事等委託契約", "mokuteki"),
        ("easy", "content", "区長が2026年9月16日に提出", "submit"),
        ("easy", "content", "ESCO事業の説明（調査・設計・施工・効果の検証・助言・効果保証等）", "gaiyo"),
        ("easy", "content", "工事場所", "basho"),
        ("easy", "content", "契約の方法", "houhou"),
        ("easy", "content", "契約金額", "kingaku"),
        ("easy", "content", "相手方・住所・代表・資本金", "ov_aite"),
        ("easy", "content", "仮契約2026年7月31日（金）、本契約は議決日の翌日", "tsukihi"),
        ("easy", "content", "契約期間は2033年（令和15年）2月28日まで", "kikan"),
        ("easy", "content", "支払いは2027〜2032年度（令和9〜14年度）の債務負担行為", "shishutsu"),
        ("easy", "content", "同じしくみの契約がほかに2つ、あわせて3つ", "hokano"),
        *pending("easy"),
        ("easy", "content", "施設一覧、電気代の削減、年度ごとの額、入札の状況は書かれていない", None),

        ("normal", "title", "見出し: 照明をESCO事業でLED化する委託契約", "mokuteki"),
        ("normal", "summary", "要約: ESCO事業による工事等委託契約", "gaiyo"),
        ("normal", "summary", "要約: 契約金額・相手方・方法", "aite"),
        ("normal", "summary", "要約: 契約期間", "kikan"),
        ("normal", "summary", "要約: 令和9〜14年度の債務負担行為", "shishutsu"),
        ("normal", "content", "議決を求める議案", "mokuteki"),
        ("normal", "content", "提出日", "submit"),
        ("normal", "content", "工事概要の説明", "gaiyo"),
        ("normal", "content", "工事場所", "basho"),
        ("normal", "content", "契約の方法", "houhou"),
        ("normal", "content", "契約金額", "kingaku"),
        ("normal", "content", "相手方", "ov_aite"),
        ("normal", "content", "契約月日", "tsukihi"),
        ("normal", "content", "契約期間", "kikan"),
        ("normal", "content", "支出科目等", "shishutsu"),
        ("normal", "content", "関連議案（第73〜75号）", "hokano"),
        *pending("normal"),
        ("normal", "content", "議決後は議決日の翌日に本契約", "tsukihi"),
        ("normal", "content", "施設一覧、削減見込み、効果保証、年度額、入札状況は書かれていない", None),

        ("hard", "title", "見出し: 議案名", "mokuteki"),
        ("hard", "summary", "要約: 方法・相手方・金額", "aite"),
        ("hard", "summary", "要約: 工事場所・契約期間", "basho"),
        ("hard", "summary", "要約: 支出科目等", "shishutsu"),
        ("hard", "content", "提出日・提出者", "submit"),
        ("hard", "content", "議案本文の前文", "mokuteki"),
        ("hard", "content", "提案理由", "reason"),
        ("hard", "content", "契約の方法", "houhou"),
        ("hard", "content", "契約金額", "kingaku"),
        ("hard", "content", "契約の相手方", "aite"),
        ("hard", "content", "資本金等（概要資料）", "ov_aite"),
        ("hard", "content", "工事場所", "basho"),
        ("hard", "content", "契約月日", "tsukihi"),
        ("hard", "content", "契約期間", "kikan"),
        ("hard", "content", "工事概要", "gaiyo"),
        ("hard", "content", "支出科目等（各年度の金額の記載はない）", "shishutsu"),
        ("hard", "content", "同種の議案3件", "hokano"),
        *pending("hard"),
        ("hard", "content", "施設一覧、削減見込み、効果保証、各年度額、入札状況は資料にない", None),
    ]
    BILLS.append(dict(slug=f"shinjuku-2026-r3-gian-{n}", prefix=f"R{n}", facts=F, claims=C, main=p))

# 第73〜75号議案の表で他の2件の値も参照する（hard「同種の議案」）ため、他議案の fact を追加する
for b in BILLS[-3:]:
    for o in ESCO:
        b["facts"][f"other{o['n']}"] = ("OJ", f"議決案件関係 第{o['n']}号議案", OV_LINES[o["n"]][1] + " … " + OV_LINES[o["n"]][2].split(" … ")[1])
    b["claims"].append(("hard", "content", "同種の議案の表の契約金額・相手方（第73〜75号）", "other73"))
    b["claims"].append(("hard", "content", "同種の議案の表（第74号）", "other74"))
    b["claims"].append(("hard", "content", "同種の議案の表（第75号）", "other75"))

# ---------------------------------------------------------------------------
# 第76号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P76"),
    "mokuteki": ("P76", "議案本文 前文", "道路改良工事（江戸川橋通り第Ⅱ期）施行のため、下記のとおり請負契約を締結する"),
    "houhou": ("P76", "議案本文 2 契約の方法", "制限付一般競争入札による契約"),
    "kingaku": ("P76", "議案本文 3 契約金額", "4億6,970万円"),
    "aite": ("P76", "議案本文 4 契約の相手方", "東京都新宿区新宿一丁目14番5号 … 常盤工業株式会社 … 執行役員支店長 … 東京支店 … 福岳 … 雄一郎"),
    "shishutsu": ("P76", "議案本文 5 支出科目等", "令 和 8 年 度 区一般 会 計 歳 出 土木費 … 道路橋りょう費 道路新設改良費 … 工事請 負 費 … 道路橋りょう費 受託事業費 … 令 和 9 年 度 債務負 担 行 為 … 令 和 10 年 度 債務負 担 行 為"),
    "reason": ("P76", "提案理由", "道路改良工事（江戸川橋通り第Ⅱ期）を施行する必要があるため"),
    "gaiyo": ("OJ", "議決案件関係 第76号議案 1 工事概要", "⑴ 土工 一式 … ⑵ 仮設工 一式 … ⑶ 排水施設工 一式 … ⑷ 街築工 一式 … ⑸ 舗装工 一式 … ⑹ 交通安全施設工 一式 … ⑺ 下水道施設工 一式"),
    "basho": ("OJ", "議決案件関係 第76号議案 2 工事場所", "東京都新宿区天神町 63 番地先から文京区関口一丁目 21 番先まで"),
    "tsukihi": ("OJ", "議決案件関係 第76号議案 3 契約月日", "仮契約 令和 8 年 8 月 21 日（金） … 本契約 議決日の翌日"),
    "koki": ("OJ", "議決案件関係 第76号議案 4 工期", "本契約締結日の翌日から令和 10 年 12 月 13 日まで"),
    "ov_aite": ("OJ", "議決案件関係 第76号議案 7 契約の相手方", "常盤工業株式会社 東京支店 … 執行役員支店長 福岳 雄一郎 … 資本金 1 億円"),
    "listpage": ("SUB", "提出議案一覧ページ 条例案等（全文）", "第76号議案　道路改良工事（江戸川橋通り第2)期）請負契約"),
}
std(76, "R76", "P76", F, [
    ("easy", "title", "見出し: 江戸川橋通りの道路改良工事の契約", "mokuteki"),
    ("easy", "summary", "要約: 江戸川橋通り第Ⅱ期の道路改良工事の契約", "mokuteki"),
    ("easy", "summary", "要約: 金額4億6,970万円、相手は常盤工業株式会社", "aite"),
    ("easy", "summary", "要約: 工期は2028年12月13日まで", "koki"),
    ("easy", "content", "道路改良工事（江戸川橋通り第Ⅱ期）の請負契約", "mokuteki"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "工事内容7項目（いずれも一式）", "gaiyo"),
    ("easy", "content", "工事場所", "basho"),
    ("easy", "content", "契約の方法", "houhou"),
    ("easy", "content", "契約金額", "kingaku"),
    ("easy", "content", "相手方・住所・代表", "aite"),
    ("easy", "content", "資本金1億円", "ov_aite"),
    ("easy", "content", "仮契約2026年8月21日（金）、本契約は議決日の翌日", "tsukihi"),
    ("easy", "content", "工期は2028年（令和10年）12月13日まで", "koki"),
    ("easy", "content", "2026年度は土木費の道路新設改良費・受託事業費の工事請負費、2027・2028年度は債務負担行為", "shishutsu"),
    *pending("easy"),
    ("easy", "content", "交通規制、年度ごとの額、受託事業費の内容、入札の状況は書かれていない", None),
], [
    ("normal", "title", "見出し: 江戸川橋通り第Ⅱ期の道路改良工事の請負契約", "mokuteki"),
    ("normal", "summary", "要約: 工事場所", "basho"),
    ("normal", "summary", "要約: 金額・相手方・方法", "aite"),
    ("normal", "summary", "要約: 工期", "koki"),
    ("normal", "content", "議決を求める議案", "mokuteki"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "工事概要", "gaiyo"),
    ("normal", "content", "工事場所", "basho"),
    ("normal", "content", "契約の方法", "houhou"),
    ("normal", "content", "契約金額", "kingaku"),
    ("normal", "content", "相手方", "ov_aite"),
    ("normal", "content", "契約月日", "tsukihi"),
    ("normal", "content", "工期", "koki"),
    ("normal", "content", "支出科目等", "shishutsu"),
    *pending("normal"),
    ("normal", "content", "議決後は議決日の翌日に本契約", "tsukihi"),
    ("normal", "content", "交通規制、年度額、受託事業費の委託元、入札状況は書かれていない", None),
], [
    ("hard", "title", "見出し: 議案名", "mokuteki"),
    ("hard", "summary", "要約: 方法・相手方・金額", "aite"),
    ("hard", "summary", "要約: 工事場所・工期", "basho"),
    ("hard", "summary", "要約: 支出科目等", "shishutsu"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "議案本文の前文", "mokuteki"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "件名表記: 一覧ページは「第2)期」", "listpage"),
    ("hard", "content", "契約の方法", "houhou"),
    ("hard", "content", "契約金額", "kingaku"),
    ("hard", "content", "契約の相手方", "aite"),
    ("hard", "content", "資本金", "ov_aite"),
    ("hard", "content", "工事場所", "basho"),
    ("hard", "content", "契約月日", "tsukihi"),
    ("hard", "content", "工期", "koki"),
    ("hard", "content", "工事概要", "gaiyo"),
    ("hard", "content", "支出科目等（各年度の金額の記載はない）", "shishutsu"),
    *pending("hard"),
    ("hard", "content", "延長・幅員、受託事業費の内容、年度額、交通規制、入札状況、第Ⅰ期との関係は資料にない", None),
])

# ---------------------------------------------------------------------------
# 第77号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P77"),
    "mokuteki": ("P77", "議案本文 1 買入れの目的", "現行イントラネットシステム及び情報システム統合基盤の継続 … 運用用"),
    "list1": ("P77", "議案本文 2 種類及び数量", "M365 E3 Original Sub Gov Per User 4,382ライセンス … Defender Suite Sub Gov Per User 4,422ライセンス … Exchange Online P1 Sub Gov Per User 795ライセンス … EOA Exchange Online Sub Gov Per User 795ライセンス … Defender O365 P2 Sub Gov Per User 795ライセンス … Defender Endpoint Server Sub 95ライセンス"),
    "list2": ("P77", "議案本文 2 種類及び数量", "Office Professional Plus ALng LSA 197ライセンス … Azure prepayment 1,540ライセンス … Azure Standard Support 1ライセンス … SQL Server Standard Core ALng LSA 2L 13ライセンス … D365 Team Members Sub Per User 4,185ライセンス … D365 Customer Service Sub Per User 10ライセンス … Power BI Pro Sub Gov Per User 10ライセンス"),
    "list3": ("P77", "議案本文 2 種類及び数量", "CIS Suite Datacenter Core ALng LSA 2L 148ライセンス … CIS Suite Standard Core ALng LSA 2L 40ライセンス … Azure prepayment 100ライセンス … Azure Standard Support 1ライセンス … CIS Suite Datacenter Core ALng LSA 2L 210ライセンス … SQL Server Enterprise Core ALng LSA 2L 25ライセンス"),
    "list7": ("P77", "議案本文 2 種類及び数量 ⑺・⒂", "M365 E5 ShrdSvr ALNG SubsVL MVL Gov PerUsr（Original） 15ラ … Power Pages Anonymous Users T1 Sub（500User/Site/Mo） 195ラ"),
    "kingaku": ("P77", "議案本文 3 買入金額", "5億7,062万7,369円"),
    "reason": ("P77", "提案理由", "現行イントラネットシステム及び情報システム統合基盤を引き続 … き運用するため、マイクロソフト社ソフトウェアライセンスを買い … 入れる必要があるため"),
    "youto": ("OJ", "議決案件関係 第77号議案 1 概要", "現行イントラネットシステム用クラウド M365、パソコン OS ライセンス … 現行イントラネットシステム用セキュリティライセンス … 現行イントラネットシステム用共有メール BOX 用ライセンス … 現行イントラネットシステム用 Azure 利用ライセンス … 区民意見 FAQ 用 CRM ライセンス … 区公式ホームページ環境用 Azure 利用ライセンス … Server ライセンス及び SystemCenter ライセンス"),
    "youto2": ("OJ", "議決案件関係 第77号議案 1 概要", "現行イントラネットシステム用共有メール BOX バックアップ用ライセンス … 現行イントラネットシステム用共有メール BOX 用セキュリティライセンス … 現行イントラネットシステム Server 用ウイルス対策ライセンス … 現行イントラネットシステムクラウド検証用ライセンス … 現行イントラネットシステムパソコン用 Office ライセンス … 現行イントラネットシステム用 Azure 技術問合せ用サポートライセンス … 現行イントラネットシステム職員ポータル用ライセンス … 区民意見 FAQ 用 CRM 管理者用ライセンス … 区民意見 FAQ 用 CRM 外部 WEB ページ用ライセンス … 旧イントラネットシステム Server 監視用ライセンス … 区公式ホームページ環境用 Azure 技術問合せ用サポートライセンス … SQL ライセンス"),
    "datacenter": ("OJ", "議決案件関係 第77号議案 ⒃⒇", "CIS Suite DataCenter Core ALng LSA 2L 148 ライセンス"),
    "keiyaku": ("OJ", "議決案件関係 第77号議案 2〜7", "納 入 場 所 新宿区指定の場所 … 仮契約 令和 8 年 8 月 19 日（水） … 本契約 議決日の翌日 … 本契約締結日の翌日から令和 8 年 12 月 28 日まで … 指名競争入札 … 5 億 7,062 万 7,369 円"),
    "aite": ("OJ", "議決案件関係 第77号議案 7 契約の相手方", "東京都千代田区飯田橋二丁目 18 番 4 号 … 株式会社大塚商会 LA 事業部公共グループ … グループ長 浅井 秀雄 … 資本金 103 億 7,485 万 1,000 円"),
}
std(77, "R77", "P77", F, [
    ("easy", "title", "見出し: 区のシステムを使い続けるためのライセンスを買う", "mokuteki"),
    ("easy", "summary", "要約: 現行システムの継続運用のため", "reason"),
    ("easy", "summary", "要約: マイクロソフト社のライセンスを買う", "reason"),
    ("easy", "summary", "要約: 5億7,062万7,369円", "kingaku"),
    ("easy", "summary", "要約: 相手は株式会社大塚商会", "aite"),
    ("easy", "content", "イントラネットシステムと情報システム統合基盤を使い続ける", "mokuteki"),
    ("easy", "content", "マイクロソフト社のライセンスを買う", "reason"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "21種類（⑴〜(21)）", "list3"),
    ("easy", "content", "多いもの: M365 E3 4,382、Defender Suite 4,422", "list1"),
    ("easy", "content", "多いもの: D365 Team Members 4,185、Azure prepayment 1,540", "list2"),
    ("easy", "content", "用途: パソコンOS・M365、セキュリティ、共有メール、区民意見FAQ、公式ホームページ", "youto"),
    ("easy", "content", "買入金額", "kingaku"),
    ("easy", "content", "指名競争入札、納入場所、仮契約2026年8月19日（水）、本契約、納期2026年12月28日", "keiyaku"),
    ("easy", "content", "相手方・住所・代表・資本金", "aite"),
    *pending("easy"),
    ("easy", "content", "利用期間、単価、入札参加者は書かれていない", None),
], [
    ("normal", "title", "見出し: 継続運用のためのマイクロソフト社ライセンスの買入れ", "mokuteki"),
    ("normal", "summary", "要約: 21種類を5億7,062万7,369円で買い入れる", "kingaku"),
    ("normal", "summary", "要約: 継続運用のため", "reason"),
    ("normal", "summary", "要約: 大塚商会、指名競争入札、納期", "keiyaku"),
    ("normal", "content", "議決を求める議案", "reason"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "21種類", "list3"),
    ("normal", "content", "主なライセンスと数量（M365 E3、Defender Suite、Exchange Online ほか各795）", "list1"),
    ("normal", "content", "主なライセンスと数量（Azure prepayment 1,540・D365 Team Members 4,185）", "list2"),
    ("normal", "content", "主なライセンスと数量（Azure prepayment 100・CIS Suite Datacenter 210）", "list3"),
    ("normal", "content", "用途", "youto"),
    ("normal", "content", "買入金額", "kingaku"),
    ("normal", "content", "契約の方法・納入場所・契約月日・納期", "keiyaku"),
    ("normal", "content", "相手方", "aite"),
    *pending("normal"),
    ("normal", "content", "議決後は議決日の翌日に本契約", "keiyaku"),
    ("normal", "content", "利用期間、単価、指名の理由と業者は書かれていない", None),
], [
    ("hard", "title", "見出し: 議案名", "mokuteki"),
    ("hard", "summary", "要約: 継続運用のため21種類を買入れ", "mokuteki"),
    ("hard", "summary", "要約: 買入金額", "kingaku"),
    ("hard", "summary", "要約: 方法・相手方・納期（概要資料）", "keiyaku"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "買入れの目的", "mokuteki"),
    ("hard", "content", "買入金額", "kingaku"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "種類及び数量 ⑴〜⑹", "list1"),
    ("hard", "content", "種類及び数量 ⑺・⒂", "list7"),
    ("hard", "content", "種類及び数量 ⑻〜⒁", "list2"),
    ("hard", "content", "種類及び数量 ⒃〜(21)", "list3"),
    ("hard", "content", "用途（主なもの）", "youto"),
    ("hard", "content", "用途（その他）", "youto2"),
    ("hard", "content", "概要資料は「DataCenter」と表記", "datacenter"),
    ("hard", "content", "納入場所・契約月日・納期・方法", "keiyaku"),
    ("hard", "content", "相手方", "aite"),
    *pending("hard"),
    ("hard", "content", "利用期間・単価、支出科目等、指名の理由等、旧システムの監視ライセンスの理由は資料にない", None),
])

# ---------------------------------------------------------------------------
# 第78号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P78"),
    "zenbun": ("P78", "議案本文 前文", "下記のとおり遺贈により生じた権利を放棄する"),
    "kenri": ("P78", "議案本文 1 放棄する権利", "遺贈者の有する財産について遺贈を受ける権利"),
    "izosha": ("P78", "議案本文 2 遺贈者", "東京都新宿区（記載削除）"),
    "yuigon": ("P78", "議案本文 3 遺言の主たる内容", "グラフィック・デザイン博物館として活用することを条件に、遺 … 贈者の有する不動産を区に遺贈する"),
    "riyu": ("P78", "議案本文 4 放棄する理由", "遺贈の対象となる不動産について、遺贈者の遺志に応えて活用 … することが困難であるため"),
    "reason": ("P78", "提案理由", "遺贈により生じた権利を放棄する必要があるため"),
    "ov": ("OJ", "議決案件関係 第78号議案", "次のとおり遺贈により生じた権利を放棄する。 … Ａ（住所地：東京都新宿区）"),
}
std(78, "R78", "P78", F, [
    ("easy", "title", "見出し: 遺贈を受ける権利を放棄する", "zenbun"),
    ("easy", "summary", "要約: 遺言で区に不動産を遺贈", "yuigon"),
    ("easy", "summary", "要約: グラフィック・デザイン博物館としての活用が条件", "yuigon"),
    ("easy", "summary", "要約: 活用が困難", "riyu"),
    ("easy", "summary", "要約: 受け取る権利を放棄", "kenri"),
    ("easy", "content", "遺言で不動産が区に遺贈された", "yuigon"),
    ("easy", "content", "遺贈を受ける権利を放棄する", "kenri"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "条件はグラフィック・デザイン博物館として活用すること", "yuigon"),
    ("easy", "content", "遺贈者の住所は新宿区、氏名は記載削除", "izosha"),
    ("easy", "content", "理由: 遺志に応えて活用することが困難", "riyu"),
    *pending("easy"),
    ("easy", "content", "不動産の場所・広さ・価額、困難の具体的理由、放棄後の扱いは書かれていない", None),
], [
    ("normal", "title", "見出し: グラフィック・デザイン博物館を条件とする遺贈を受ける権利の放棄", "yuigon"),
    ("normal", "summary", "要約: 遺言の内容と放棄", "yuigon"),
    ("normal", "summary", "要約: 放棄の理由", "riyu"),
    ("normal", "content", "議決を求める議案", "zenbun"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "放棄する権利", "kenri"),
    ("normal", "content", "遺贈者（住所地は新宿区、氏名等は記載削除）", "izosha"),
    ("normal", "content", "遺言の主たる内容", "yuigon"),
    ("normal", "content", "放棄する理由", "riyu"),
    ("normal", "content", "提案理由", "reason"),
    *pending("normal"),
    ("normal", "content", "不動産の所在等、判断理由、検討内容、放棄後の扱いは書かれていない", None),
], [
    ("hard", "title", "見出し: 議案名", "zenbun"),
    ("hard", "summary", "要約: 遺言の内容と放棄", "yuigon"),
    ("hard", "summary", "要約: 放棄の理由", "riyu"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "議案本文の前文", "zenbun"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "1 放棄する権利", "kenri"),
    ("hard", "content", "2 遺贈者", "izosha"),
    ("hard", "content", "3 遺言の主たる内容", "yuigon"),
    ("hard", "content", "4 放棄する理由", "riyu"),
    ("hard", "content", "概要資料の表記（Ａ、住所地：東京都新宿区）", "ov"),
    *pending("hard"),
    ("hard", "content", "不動産の詳細、遺言の効力発生時期、判断理由、放棄後の帰属、議決の根拠規定は資料にない", None),
])

# ---------------------------------------------------------------------------
# 第79号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P79"),
    "zenbun": ("P79", "議案本文 前文", "自動車事故による損害賠償の額を、下記のとおり決定する"),
    "aite": ("P79", "議案本文 1 相手方", "東京都稲城市（記載削除）"),
    "jiko": ("P79", "議案本文 2 事故の概要", "令和7年6月28日午前9時48分頃、清掃車両にて首都高速道 … 路を走行中、2台前の車両が無理な車線変更をするため急ブレー … キをかけたことから、1台前の車両が急ブレーキをかけて急停車 … した。清掃車両も急ブレーキをかけたが間に合わず、1台前の車 … 両と接触したものである"),
    "gaku": ("P79", "議案本文 3 損害賠償額", "216万8,065円 … 人身損害 110万6,972円 … 物件損害 106万1,093円"),
    "reason": ("P79", "提案理由", "区が保有する自動車の事故による損害賠償の額を定める必要があ … るため"),
    "ov": ("OJ", "議決案件関係 第79号議案", "Ａ（住所地：東京都稲城市） … 1 台前の車両が急ブレ … ーキをかけて停車した。 … 216 万 8,065 円"),
}
std(79, "R79", "P79", F, [
    ("easy", "title", "見出し: 清掃車の事故の損害賠償の額を決める", "zenbun"),
    ("easy", "summary", "要約: 首都高速道路で前の車に接触", "jiko"),
    ("easy", "summary", "要約: 216万8,065円を払う", "gaku"),
    ("easy", "content", "区が保有する自動車の事故", "reason"),
    ("easy", "content", "損害賠償の額を決定する", "zenbun"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "2025年（令和7年）6月28日（土）午前9時48分ごろ、首都高速道路、清掃車両", "jiko"),
    ("easy", "content", "事故の経過（2台前の車線変更・急ブレーキ、1台前の急停車、接触）", "jiko"),
    ("easy", "content", "相手方の住所は稲城市、氏名は記載削除", "aite"),
    ("easy", "content", "人身損害110万6,972円、物件損害106万1,093円、合計216万8,065円", "gaku"),
    *pending("easy"),
    ("easy", "content", "過失割合、保険、けがの程度は書かれていない", None),
], [
    ("normal", "title", "見出し: 清掃車両の事故による損害賠償額216万8,065円の決定", "gaku"),
    ("normal", "summary", "要約: 事故の日と場所", "jiko"),
    ("normal", "summary", "要約: 額と内訳", "gaku"),
    ("normal", "content", "区が保有する自動車の事故による損害賠償の額を定める", "reason"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "事故の概要（引用）", "jiko"),
    ("normal", "content", "相手方", "aite"),
    ("normal", "content", "損害賠償額の内訳", "gaku"),
    *pending("normal"),
    ("normal", "content", "過失割合、財源、けがの程度、運転者の所属は書かれていない", None),
], [
    ("hard", "title", "見出し: 議案名", "zenbun"),
    ("hard", "summary", "要約: 事故の概要", "jiko"),
    ("hard", "summary", "要約: 額と内訳", "gaku"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "議案本文の前文", "zenbun"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "相手方", "aite"),
    ("hard", "content", "概要資料の相手方表記", "ov"),
    ("hard", "content", "事故の概要（引用）", "jiko"),
    ("hard", "content", "概要資料は「停車した」と記す", "ov"),
    ("hard", "content", "損害賠償額と内訳", "gaku"),
    *pending("hard"),
    ("hard", "content", "過失割合・示談、財源、負傷の程度・物件、運転者の所属・求償、議決の根拠規定は資料にない", None),
])

# ---------------------------------------------------------------------------
# 第80号議案
# ---------------------------------------------------------------------------
F = {
    "session": SESSION, "submit": JOREI_SUBMIT("P80"),
    "zenbun": ("P80", "議案本文 前文", "下記のとおり建物明渡し等の請求に関する訴えを提起する"),
    "tojisha": ("P80", "議案本文 1 訴訟当事者", "原告 東京都新宿区歌舞伎町一丁目4番1号 … 新宿区 … 被告（賃借人） … 東京都新宿区（記載削除） … 被告（連帯保証人） … 東京都荒川区（記載削除）"),
    "k1": ("P80", "議案本文 2⑴", "令和6年10月25日、被 … 告（賃借人）（以下「賃借人」という。）に対して、区が新宿 … 区立住宅管理条例（平成9年新宿区条例第25号。以下「条例」 … という。）に基づき設置し、及び管理している … 特定住宅 … 令和6年11 … 月7日に本件建物へ住民票を異動の上、その占有を開始した"),
    "k2": ("P80", "議案本文 2⑵", "使用許可日における本件建物の使用料の 3か月分を限度とし … て、賃借人が本件建物の使用により生じた一切の債務の履行に … 関し、連帯して保証する旨約した"),
    "k3": ("P80", "議案本文 2⑶", "入居当時から本件建物の使用料及び共益費（以下 … 「使用料等」という。）を滞納し、区の度重なる督促及び催告 … 並びに納付交渉により一部納付はあったものの、令和6年12月 … 分から使用料等を一切納付しなくなり、滞納が累積していった"),
    "k4": ("P80", "議案本文 2⑷", "令和7年9月19日に法律事務所へ債権の回 … 収を委託し、同年11月25日に法律事務所から賃借人及び連帯 … 保証人宛てで督促状を送付したが、何らの連絡もなかった"),
    "k5": ("P80", "議案本文 2⑸", "令和8年3月16日に法律事務所から賃借人及び連帯保証人 … 宛てで督促状（最後通牒）を送付したが、その期日までに納付 … 及び連絡はなかった。 … 同年4月24日に督促状を再送し、連帯保証人から法律事務 … 所に一度連絡があったものの、その後音信不通となった"),
    "k6": ("P80", "議案本文 2⑹", "条例第37条第1項第11号の規定に基づ … き、令和8年6月19日をもって本件建物の使用許可を取り消 … し、同年7月10日を期限とする本件建物の明渡しを請求した"),
    "k7": ("P80", "議案本文 2⑺", "賃借人は本件建物の明渡しを行わず、また、当該使 … 用料等滞納分の納付も行わないまま今日に至っている"),
    "k8": ("P80", "議案本文 2⑻", "賃借人に対し、本件建物の明渡しを求めるほ … か、賃借人及び連帯保証人に対し、使用料等の滞納分、計285 … 万9,100円及び条例第38条第4項の規定に基づく使用許可取 … 消日の翌日から本件建物の明渡しを行う日までの期間につい … て、毎月、使用料限度額の2倍の金銭の支払並びに仮執行の宣 … 言を求める訴えを提起する"),
    "hoshin": ("P80", "議案本文 3 訴訟遂行の方針", "本件訴訟において必要がある場合は、和解及び上訴をすること … ができるものとする"),
    "reason": ("P80", "提案理由", "特定住宅に係る建物明渡し等の請求に関し、訴えを提起する必要 … があるため"),
    "ov": ("OJ", "議決案件関係 第80号議案", "Ａは、令和 6 年 10 月から特定住宅の使用許可を受け、 … 居住を開始した。"),
}
std(80, "R80", "P80", F, [
    ("easy", "title", "見出し: 区立住宅の明渡しを求める訴えを提起する", "zenbun"),
    ("easy", "summary", "要約: 特定住宅の使用料等の滞納", "k3"),
    ("easy", "summary", "要約: 使用許可の取消し", "k6"),
    ("easy", "summary", "要約: 明渡しと滞納分285万9,100円の支払い等を求めて提訴", "k8"),
    ("easy", "content", "区立住宅（特定住宅）の使用料等を払っていない", "k3"),
    ("easy", "content", "明渡しと支払いを求めて訴えを提起", "zenbun"),
    ("easy", "content", "区長が2026年9月16日に提出", "submit"),
    ("easy", "content", "原告は新宿区、被告は賃借人と連帯保証人、住所は新宿区・荒川区、氏名は記載削除", "tojisha"),
    ("easy", "content", "新宿区立住宅管理条例に基づく特定住宅、2024年（令和6年）10月25日（金）許可、11月7日（木）住民票異動・占有開始", "k1"),
    ("easy", "content", "入居当時から滞納、一部納付あり、2024年12月分から一切納付せず", "k3"),
    ("easy", "content", "2025年（令和7年）9月19日（金）法律事務所へ委託、11月25日（火）督促状、連絡なし", "k4"),
    ("easy", "content", "2026年（令和8年）3月16日（月）最後通牒、4月24日（金）連帯保証人へ再送、一度連絡後に音信不通", "k5"),
    ("easy", "content", "2026年6月19日（金）使用許可取消し、7月10日（金）が明渡し期限", "k6"),
    ("easy", "content", "明渡し・納付のないまま", "k7"),
    ("easy", "content", "連帯保証の限度は使用料の3か月分", "k2"),
    ("easy", "content", "明渡し、285万9,100円、取消日の翌日から明渡し日まで毎月使用料限度額の2倍（条例第38条第4項）、仮執行の宣言", "k8"),
    ("easy", "content", "和解・上訴をすることができる", "hoshin"),
    *pending("easy"),
    ("easy", "content", "保証限度との関係、月額使用料、特定住宅の内容は書かれていない", None),
], [
    ("normal", "title", "見出し: 区立特定住宅の明渡し等を求める訴えの提起", "zenbun"),
    ("normal", "summary", "要約: 滞納と使用許可取消し後の不明渡し", "k7"),
    ("normal", "summary", "要約: 明渡し・285万9,100円・損害金・仮執行の宣言", "k8"),
    ("normal", "summary", "要約: 和解・上訴", "hoshin"),
    ("normal", "content", "議決を求める議案", "zenbun"),
    ("normal", "content", "提出日", "submit"),
    ("normal", "content", "訴訟の当事者", "tojisha"),
    ("normal", "content", "経過⑴", "k1"),
    ("normal", "content", "経過⑵", "k2"),
    ("normal", "content", "経過⑶", "k3"),
    ("normal", "content", "経過⑷", "k4"),
    ("normal", "content", "経過⑸", "k5"),
    ("normal", "content", "経過⑹", "k6"),
    ("normal", "content", "経過⑺", "k7"),
    ("normal", "content", "区が求めること", "k8"),
    ("normal", "content", "訴訟遂行の方針", "hoshin"),
    *pending("normal"),
    ("normal", "content", "保証限度との関係、月額使用料、特定住宅の制度内容は書かれていない", None),
], [
    ("hard", "title", "見出し: 議案名", "zenbun"),
    ("hard", "summary", "要約: 使用許可の取消し", "k6"),
    ("hard", "summary", "要約: 請求の内容", "k8"),
    ("hard", "summary", "要約: 和解及び上訴の権限", "hoshin"),
    ("hard", "content", "提出日・提出者", "submit"),
    ("hard", "content", "議案本文の前文", "zenbun"),
    ("hard", "content", "提案理由", "reason"),
    ("hard", "content", "訴訟当事者", "tojisha"),
    ("hard", "content", "⑴", "k1"),
    ("hard", "content", "⑵", "k2"),
    ("hard", "content", "⑶", "k3"),
    ("hard", "content", "⑷", "k4"),
    ("hard", "content", "⑸", "k5"),
    ("hard", "content", "⑹", "k6"),
    ("hard", "content", "⑺", "k7"),
    ("hard", "content", "⑻", "k8"),
    ("hard", "content", "訴訟遂行の方針", "hoshin"),
    ("hard", "content", "概要資料は「令和6年10月から」とする", "ov"),
    *pending("hard"),
    ("hard", "content", "保証限度との関係、月額使用料・限度額、特定住宅の制度、条文、管轄裁判所・提起時期、議決の根拠規定は資料にない", None),
])
